# Generated by Django 4.2 on 2023-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_alter_bookorder_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('cat', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stat', models.CharField(max_length=50)),
            ],
        ),
    ]
