# Generated by Django 4.2 on 2023-05-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='cat',
            field=models.CharField(choices=[('1', 'Veg'), ('2', 'Non-veg')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='foodname',
            field=models.CharField(choices=[('1', 'Punjabi'), ('2', 'Maharashtrian'), ('3', 'South Indian'), ('4', 'Chinese'), ('5', 'Biryani')], max_length=50, verbose_name='Food Name'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='qty',
            field=models.IntegerField(verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cat',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='stat',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
    ]
